### ISSUE TITLE
feature request with missing values

### ISSUE THREAD

**Issue by mdsumner** [bryanhanson/exCon#3]
Hi, when there are NAs the margin profiles may be missing - depending on the distribution of the missing values. It would be nice if the plot reported this as a possible issue, or better dealt with the NAs and put in markers to show the missing information in the margins. 

``` R
library(exCon)
data(volcano)
v1 <- volcano
v1[10] <- NA_real_
## this doesn't show a problem
exCon(v1, minify = FALSE)

## another example
v2 <- volcano
v2[1:10, 1:5] <- NA_real_
## this silently shows no margin profiles
exCon(v2, minify = FALSE)
```

**Comment by bryanhanson** [comment]
Sorry for the delay in responding (too much work).  I don't know why the 1st example actually works, but it does and it throws no JS errors.  The 2nd example is throwing errors in the JS.  The profiles are actually taken directly from the matrix so I'm not surprised JS doesn't know how to connect the data.

I'm not sure how one would draw the profiles when there is missing data.  I guess one would have to interpolate the original matrix first and substitute it before continuing.

Is this a common situation you encounter?
